const { withGradleProperties } = require("expo/config-plugins");

// Release builds run out of Metaspace with the default 512 MB (lintVitalAnalyzeRelease).
// android/ is generated by prebuild, so set the Gradle JVM memory here instead.
module.exports = function withGradleMemory(config) {
  return withGradleProperties(config, (cfg) => {
    const key = "org.gradle.jvmargs";
    const value = "-Xmx4096m -XX:MaxMetaspaceSize=1536m";
    const existing = cfg.modResults.find((p) => p.type === "property" && p.key === key);
    if (existing) existing.value = value;
    else cfg.modResults.push({ type: "property", key, value });
    return cfg;
  });
};
